### ISSUE TITLE
[BUG] Weird item dupe

### ISSUE THREAD

**Issue by HSIbrahim** [PluginBugs/Issues-Real-DualWield#10]
So the 1.19.4 version of minecraft is making issues with epic backpack (Vanilla). When you right click the backpack then drop the item close it reopen it, there will be two. The one on the floor and there is one in backpack it never left.

Video: https://streamable.com/9g9ww5

Steps:
1. Open 1.19.4 Vanilla / Lunar client 1.19.4
2. Right click "Right click the backpack make sure there is items in that backpack."
3. Drag the item you want to duplicate then drop it.
4. Close the backpack then reopen it. It will spawn in again in your backpack. There will be 2 one on the floor and other one spawnned in your backpack

Info:
 - Server version: 1.17.1
 - Client version: 1.19.4
 - Plugin version: 1.3.16-r2

Please fix this quick

**Comment by LoneDev6** [comment]
This is not the issues repository for epic backpacks, it's for real dual wield.
Please report it in the correct place.

Anyway DUPLICATION issues must be reported privately on the forum private area, not publicly on Github.
https://forum.devs.beer/t/private-duplication-bug
