### ISSUE TITLE
Bedrock

### ISSUE THREAD

**Issue by NicDevTV** [PluginBugs/Issues-Real-DualWield#11]
Does the plugin work on a Java server with Geyser so that the Bedrock players also see e.g. the 250 sheep?

**Comment by LoneDev6** [comment]
It wasn't tested on Bedrock.

**Comment by NicDevTV** [comment]
Kann man es denn irgendwie für Bedrock testen?MFG NiclasAm 14.04.2023 um 18:00 schrieb LoneDev ***@***.***>:﻿
It wasn't tested on Bedrock.

**Comment by NicDevTV** [comment]
Can you test it on Bedrock? @LoneDev6
