### ISSUE TITLE
[BUG] Doesn't work with mining

### ISSUE THREAD

**Issue by DrkMatr1984** [PluginBugs/Issues-Real-DualWield#5]
**Describe the bug**

**To Reproduce**
1 Tried to use pickaxe in offhand to mine a grass block
2 Got Error in console, breaking was not successful in game

**Expected behavior**
The grass block break or at least no console error

**Screenshots**
[Pastebin](https://pastebin.com/DWYD0LU1)

**Info (please complete the following information):**
 - Server version: (example: paper 1.15.2) 1.18.1
 - Client version: (example: fabric 1.15.2) 1.18.1
 - Plugin version: (example: 2.0.9 do not write "latest")  1.1.36

**Additional context**

**Comment by LoneDev6** [comment]
This is not a feature of the plugin, so it's not a bug.
This is a feature request I suppose.
https://github.com/PluginBugs/Issues-Real-DualWield/issues/3
